In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
###sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]


In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [20]:
## define the vocabulary size
voc_size = 10000

In [21]:
##One hot representation(optional)

onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[8640, 8083, 280, 4065], [8640, 8083, 280, 1058], [8640, 7922, 280, 5398], [4097, 9733, 3474, 8413, 575], [4097, 9733, 3474, 8413, 9901], [7507, 8640, 601, 280, 7346], [91, 3142, 9806, 8413]]


In [22]:
#word embedding representation
from tensorflow.keras.layers import Embedding 
#from tensorflow.keras.processing import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential#first we made the sequential model
import numpy as np



In [23]:
# as we need to mke all the sentences of same length so we will use pad_sequences(to train)
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)#padding='pre' means padding will be done before the sentence means zeroes will be added before the sentence to make it of same length
print(embedded_docs)



[[   0    0    0    0 8640 8083  280 4065]
 [   0    0    0    0 8640 8083  280 1058]
 [   0    0    0    0 8640 7922  280 5398]
 [   0    0    0 4097 9733 3474 8413  575]
 [   0    0    0 4097 9733 3474 8413 9901]
 [   0    0    0 7507 8640  601  280 7346]
 [   0    0    0    0   91 3142 9806 8413]]


In [24]:
##feature representation
dim = 10#dimension of the feature

# creating the model
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')



c:\Users\aakash\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [25]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step


array([[[ 1.95646025e-02, -3.27795967e-02, -1.11000165e-02,
          3.00381295e-02,  9.83935595e-03, -9.53234360e-03,
         -9.50048119e-03, -3.03301942e-02, -1.44192688e-02,
          3.14349197e-02],
        [ 1.95646025e-02, -3.27795967e-02, -1.11000165e-02,
          3.00381295e-02,  9.83935595e-03, -9.53234360e-03,
         -9.50048119e-03, -3.03301942e-02, -1.44192688e-02,
          3.14349197e-02],
        [ 1.95646025e-02, -3.27795967e-02, -1.11000165e-02,
          3.00381295e-02,  9.83935595e-03, -9.53234360e-03,
         -9.50048119e-03, -3.03301942e-02, -1.44192688e-02,
          3.14349197e-02],
        [ 1.95646025e-02, -3.27795967e-02, -1.11000165e-02,
          3.00381295e-02,  9.83935595e-03, -9.53234360e-03,
         -9.50048119e-03, -3.03301942e-02, -1.44192688e-02,
          3.14349197e-02],
        [-4.91890572e-02, -4.57505360e-02, -2.91353706e-02,
          3.51195410e-03,  2.91876532e-02, -1.42802224e-02,
          2.84387581e-02,  1.33059919e-04,  4.052329

In [ ]:
embedded_docs[0]#in the above output we can see that the embedded_docs[0] is the first sentence and 0 inisde it convert it into 1.9 and other 0 is coverted to 3.2 and so on

array([   0,    0,    0,    0, 8640, 8083,  280, 4065])